runtime: custom
env: flex
instance_class: F1

env_variables:
  API: https://api.atg.padungsilpa.group

automatic_scaling:
  target_cpu_utilization: 0.5
  max_instances: 1
  min_instances: 0
  max_concurrent_requests: 50