version: '2'

services:
  react:
    image: node:8.6.0-slim
    container_name: react
    volumes:
      - './:/app'
    working_dir: '/app'
    command: sh -c 'npm install; npm run build; npm start;'
    ports:
      - '8080:8080'