version: '2'

services:

  proxy-server:
    image: node:8.6.0-slim
    container_name: proxy-server
    volumes:
      - './proxy-server:/'
    working_dir: '/'
    command: 'sh -c npm install; npm start;'
    ports:
      - '5000:5000'

  react:
    image: node:8.6.0-slim
    container_name: react
    depends_on: proxy-server
    volumes:
      - './:/'
    working_dir: '/'
    command: 'sh -c npm install; npm run build; npm start;'
    ports:
      '8080:8080'