apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pse-atg
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: gcr.io/kubernetes-217215/github-taweesoft-pse-atg-downloader-mobx:latest
        ports:
        - containerPort: 8080
        env:
        - name: API
          value: https://api.atg.padungsilpa.group
      restartPolicy: Always