kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  namespace: pse-atg
  name: web
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: atg-padungsilpa.group-tls # [TODO] Change this to YOUR_HOST-tls
    hosts:
    - atg.padungsilpa.group # [TODO] Change this to your host
  rules:
  - host: atg.padungsilpa.group # [TODO] Change this to your host
    http:
      paths:
      - path: /.well-known/acme-challenge/_selftest
        backend:
          serviceName: kube-lego-gce
          servicePort: 8080
      - path: /*
        backend:
          serviceName: web
          servicePort: 80