kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  namespace: pse-atg
  name: web
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - secretName: atg-padungsilpa.group-tls # [TODO] Change this to YOUR_HOST-tls
    hosts:
    - atg.padungsilpa.group # [TODO] Change this to your host
  rules:
  - host: atg.padungsilpa.group # [TODO] Change this to your host
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80