version: '3.1'

services:

    production-nginx-container:
        container_name: 'production-nginx-container'
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./production.conf:/etc/nginx/conf.d/default.conf
            - ./production-site:/usr/share/nginx/html
            - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
            - /docker-volumes/etc/letsencrypt/live/atg.padungsilpa.group/fullchain.pem:/etc/letsencrypt/live/atg.padungsilpa.group/fullchain.pem
            - /docker-volumes/etc/letsencrypt/live/atg.padungsilpa.group/privkey.pem:/etc/letsencrypt/live/atg.padungsilpa.group/privkey.pem
        restart: always
    pse-atg:
        container_name: 'pse-atg'
        image: taweesoft/pse-atg-react
        ports:
            - 8080:8080
        environment:
            - API=https://api.atg.padungsilpa.group
        restart: always